### PR TITLE
add possibility to use hostname.local

### PR DESCRIPTION
**Pull request by koraysels**
I added the possibility to use mDNS (bonjour, zeroconf, avahi)

for localdns resolution. 

This means you can switch networks without the need to set fixed ip addresses and/or reflash each tallylight.. 

helps me alot anyway. cheerio!

### CODE REVIEW

**Comment by josephdadams** [comment]
Very cool!

Is `serverIp` null/undefined if it isn't found in MDNS? Does this affect the boot up speed at all? (I'm not overly concerned about that, just curious.)

**Comment by josephdadams** [comment]
I've decided to close this. I think MDNS support is something I want to offer down the road, but I'd rather implement it in a fashion that the device can be booted up with minimal to no coding config changes required, and then the user can either select detected TA servers, or the TA server itself would also detect TA clients.

**Comment by koraysels** [comment]
Oh i didnt answer your question sorry. It does in fact work if not found or if you pick an ip instead of mdns name. Also no noticable startup delay...

**Comment by koraysels** [comment]
TA Server detection on local network would really be boss!

**Pull request closed without merging**
